/* ---------------------------------------------------------
   小6 英語（外国語・NEW HORIZON Elementary 6 の 単元を 目安に）v10.9

   ステージ
     1 自分の こと・日課（This is me. / My daily schedule）        … 1学期
     2 行きたい 国・住んで いる 町（Let's go to Italy. / My town）  … 1〜2学期
     3 夏の 思い出・生き物と かん境（Summer vacation / Creatures）  … 2学期
     4 小学校の 思い出・中学校で したい こと（My best memory）      … 3学期

   書き方は eigo5.js と 同じ（正解を choices の さきに 書く）。
   問題文の 英語は "..." の 中（よみあげの「きく」ボタンが 読む）。
   日本語の かん字は 小1〜小6 の 字だけ（smoke.js が 検査）。
   --------------------------------------------------------- */
window.MQ = window.MQ || {};

MQ.eigo6 = {
  questions: [
    /* ===== 1 自分の こと ===== */
    { stage: 1, lv: 1, unit: '自分のこと', text: '"I am good at swimming." の いみは？', choices: ['わたしは 泳ぐのが 得意です', 'わたしは 泳ぎたいです', 'わたしは 泳げません', 'わたしは 泳ぎに 行きます'], note: 'be good at 〜ing ＝ 〜が 得意だ。', hint: 'good at ＝ 得意。' },
    { stage: 1, lv: 1, unit: '自分のこと', text: '"What sport do you like?" に 合う 答えは？', choices: ['I like basketball.', 'I like red.', 'I am eleven.', 'It is Monday.'], note: 'スポーツを 聞かれて います。', hint: 'sport ＝ スポーツ。' },
    { stage: 1, lv: 1, unit: '自分のこと', text: '"My birthday is May 5th." の いみは？', choices: ['わたしの たん生日は 5月5日です', 'わたしは 5さいです', '5月5日に 会いましょう', '5時5分です'], note: 'May ＝ 5月、5th ＝ 5日。', hint: 'birthday ＝ たん生日。' },
    { stage: 1, lv: 1, unit: '自分のこと', text: '"I want to join the soccer team." の いみは？', choices: ['サッカー部に 入りたいです', 'サッカーを 見たいです', 'サッカーが 好きです', 'サッカーは むずかしいです'], note: 'want to join ＝ 入りたい。', hint: 'join ＝ 加わる。' },
    { stage: 1, lv: 2, unit: '自分のこと', text: '"I am from Osaka." の いみは？', choices: ['わたしは 大阪の 出身です', 'わたしは 大阪へ 行きます', '大阪は 遠いです', '大阪が 好きです'], note: 'be from 〜 ＝ 〜の 出身。', hint: 'from ＝ 〜から。' },
    { stage: 1, lv: 2, unit: '自分のこと', text: '"I can play the piano well." の いみは？', choices: ['わたしは ピアノを じょうずに ひけます', 'わたしは ピアノが ほしいです', 'ピアノを ひいて ください', 'ピアノは 高いです'], note: 'well ＝ じょうずに。', hint: 'can ＝ できる。' },
    { stage: 1, lv: 2, unit: '自分のこと', text: '"What do you want to be?" に 合う 答えは？', choices: ['I want to be a teacher.', 'I want a new bag.', 'I like summer.', 'I go to school.'], note: 'want to be 〜 ＝ 〜に なりたい。', hint: 'be ＝ 〜に なる。' },
    { stage: 1, lv: 3, unit: '自分のこと', text: '"I\'m good at cooking, but I\'m not good at singing." の いみは？', choices: ['料理は 得意だが 歌は 得意では ない', '料理も 歌も 得意だ', '料理も 歌も 苦手だ', '歌は 得意だが 料理は 苦手だ'], note: 'but ＝ しかし。', hint: 'but の 後に 注目。', boss: true },
    /* ===== 1 日課（一日の すごし方）===== */
    { stage: 1, lv: 1, unit: '日課', text: '"I get up at six." の いみは？', choices: ['わたしは 6時に 起きます', 'わたしは 6時に ねます', 'わたしは 6さいです', '6時に 会いましょう'], note: 'get up ＝ 起きる。', hint: 'get up ＝ 起きる。' },
    { stage: 1, lv: 1, unit: '日課', text: '"I go to bed at nine." の いみは？', choices: ['わたしは 9時に ねます', 'わたしは 9時に 起きます', '9時に 家を 出ます', '9時に 帰ります'], note: 'go to bed ＝ ねる。', hint: 'bed ＝ ベッド。' },
    { stage: 1, lv: 1, unit: '日課', text: '"I always eat breakfast." の いみは？', choices: ['わたしは いつも 朝ごはんを 食べます', 'わたしは ときどき 朝ごはんを 食べます', 'わたしは 朝ごはんを 食べません', 'わたしは 昼ごはんを 食べます'], note: 'always ＝ いつも。', hint: 'always ＝ いつも。' },
    { stage: 1, lv: 2, unit: '日課', text: '"I sometimes walk my dog." の いみは？', choices: ['わたしは ときどき 犬の 散歩を します', 'わたしは いつも 犬の 散歩を します', 'わたしは 犬と 走ります', 'わたしは 犬が 好きです'], note: 'sometimes ＝ ときどき。', hint: 'sometimes ＝ ときどき。' },
    { stage: 1, lv: 2, unit: '日課', text: '"I usually study after dinner." の いみは？', choices: ['わたしは ふだん 夕食の 後に 勉強します', 'わたしは 夕食の 前に 勉強します', 'わたしは 勉強しません', 'わたしは 夕食を 作ります'], note: 'usually ＝ ふだん、after ＝ 〜の 後。', hint: 'after ＝ 後。' },
    { stage: 1, lv: 2, unit: '日課', text: '"I never watch TV in the morning." の いみは？', choices: ['朝は けっして テレビを 見ません', '朝は いつも テレビを 見ます', '朝 テレビを 見たいです', '夜 テレビを 見ます'], note: 'never ＝ けっして 〜ない。', hint: 'never ＝ 一度も ない。' },
    { stage: 1, lv: 3, unit: '日課', text: '"What time do you leave home?" の いみは？', choices: ['何時に 家を 出ますか', '何時に 家に 帰りますか', 'どこに 住んで いますか', '家は どこですか'], note: 'leave ＝ 出る、去る。', hint: 'leave home ＝ 家を 出る。' },
    { stage: 1, lv: 3, unit: '日課', text: '「わたしは 毎日 6時に 起きます」を 英語で 言うと？', choices: ['I get up at six every day.', 'I get up six every day.', 'I am six every day.', 'I go to six every day.'], note: '時こくの 前に at を つけます。', hint: 'at ＋ 時こく。', boss: true },
    /* ===== 2 行きたい 国 ===== */
    { stage: 2, lv: 1, unit: '行きたい国', text: '"I want to go to Italy." の いみは？', choices: ['イタリアへ 行きたいです', 'イタリアが 好きです', 'イタリアに 住んで います', 'イタリアは 遠いです'], note: 'want to go to 〜 ＝ 〜へ 行きたい。', hint: 'go to ＝ 〜へ 行く。' },
    { stage: 2, lv: 1, unit: '行きたい国', text: '"Where do you want to go?" の いみは？', choices: ['どこへ 行きたいですか', 'いつ 行きますか', 'だれと 行きますか', 'なぜ 行くのですか'], note: 'Where ＝ どこ。', hint: 'Where ＝ どこ。' },
    { stage: 2, lv: 1, unit: '行きたい国', text: '"You can see the pyramids." の いみは？', choices: ['ピラミッドを 見る ことが できます', 'ピラミッドを 作れます', 'ピラミッドが 好きです', 'ピラミッドへ 行きます'], note: 'can see ＝ 見る ことが できる。', hint: 'see ＝ 見る。' },
    { stage: 2, lv: 2, unit: '行きたい国', text: '"You can eat delicious pizza." の いみは？', choices: ['おいしい ピザを 食べる ことが できます', 'ピザを 作れます', 'ピザが きらいです', 'ピザを 買いました'], note: 'delicious ＝ おいしい。', hint: 'eat ＝ 食べる。' },
    { stage: 2, lv: 2, unit: '行きたい国', text: '"Why do you want to go there?" に 合う 答えは？', choices: ['Because I like soccer.', 'Yes, I do.', 'It\'s sunny.', 'I am ten.'], note: 'Why 〜? には Because 〜. で 答えます。', hint: 'Why ＝ なぜ。' },
    { stage: 2, lv: 2, unit: '行きたい国', text: '"It\'s a beautiful country." の いみは？', choices: ['そこは 美しい 国です', 'それは 大きな 町です', 'とても 遠いです', 'よい 天気です'], note: 'country ＝ 国。', hint: 'beautiful ＝ 美しい。' },
    { stage: 2, lv: 3, unit: '行きたい国', text: '「わたしは オーストラリアへ 行きたいです。コアラを 見る ことが できます。」を 英語で 言うと？', choices: ['I want to go to Australia. You can see koalas.', 'I go to Australia. You see koalas.', 'I like Australia. I have koalas.', 'I am Australia. You are koalas.'], note: '行きたい ＝ want to go、見られる ＝ can see。', hint: '二つの 文を つなげる。', boss: true },
    /* ===== 2 住んで いる 町 ===== */
    { stage: 2, lv: 1, unit: '住んでいる町', text: '"We have a big park in our town." の いみは？', choices: ['わたしたちの 町には 大きな 公園が あります', 'わたしたちは 公園へ 行きます', '公園は 小さいです', '公園で 遊びます'], note: 'We have 〜 ＝ 〜が あります。', hint: 'have ＝ もって いる・ある。' },
    { stage: 2, lv: 1, unit: '住んでいる町', text: '"We don\'t have a zoo." の いみは？', choices: ['動物園は ありません', '動物園が あります', '動物園へ 行きません', '動物園が 好きです'], note: "don't have ＝ ない。", hint: "don't ＝ 〜ない。" },
    { stage: 2, lv: 2, unit: '住んでいる町', text: '"I want a library in my town." の いみは？', choices: ['町に 図書館が ほしいです', '図書館へ 行きます', '図書館が あります', '図書館が 好きです'], note: 'want ＝ ほしい。', hint: 'library ＝ 図書館。' },
    { stage: 2, lv: 2, unit: '住んでいる町', text: '"Our town is famous for its festival." の いみは？', choices: ['わたしたちの 町は まつりで 有名です', '町に まつりが ありません', 'まつりが 好きです', 'まつりへ 行きます'], note: 'be famous for 〜 ＝ 〜で 有名だ。', hint: 'famous ＝ 有名な。' },
    { stage: 2, lv: 2, unit: '住んでいる町', text: '"Where is the station?" に 合う 答えは？', choices: ['It\'s near the park.', 'It\'s ten o\'clock.', 'I like trains.', 'Yes, I do.'], note: '場所を 答えます。near ＝ 〜の 近く。', hint: 'Where ＝ どこ。' },
    { stage: 2, lv: 3, unit: '住んでいる町', text: '"We can enjoy shopping in my town." の いみは？', choices: ['わたしの 町では 買い物を 楽しめます', 'わたしの 町で 買い物を しました', '買い物が きらいです', '町に 店が ありません'], note: 'enjoy 〜ing ＝ 〜を 楽しむ。', hint: 'enjoy ＝ 楽しむ。' },
    { stage: 2, lv: 3, unit: '住んでいる町', text: '「わたしの 町には 川が あります」を 英語で 言うと？', choices: ['We have a river in my town.', 'We are a river in my town.', 'I river my town.', 'My town have a river.'], note: 'We have 〜 で「〜が ある」を あらわします。', hint: 'have を 使う。' },
    /* ===== 3 夏の 思い出 ===== */
    { stage: 3, lv: 1, unit: '夏の思い出', text: '"I went to the sea." の いみは？', choices: ['わたしは 海へ 行きました', 'わたしは 海へ 行きます', '海は 大きいです', '海が 好きです'], note: 'went は go の 過去の 形。', hint: 'went ＝ 行った。' },
    { stage: 3, lv: 1, unit: '夏の思い出', text: '"I ate shaved ice." の いみは？', choices: ['わたしは かき氷を 食べました', 'わたしは かき氷を 食べます', 'かき氷は つめたいです', 'かき氷が 好きです'], note: 'ate は eat の 過去の 形。', hint: 'ate ＝ 食べた。' },
    { stage: 3, lv: 1, unit: '夏の思い出', text: '"It was fun." の いみは？', choices: ['それは 楽しかったです', 'それは 楽しいです', 'それは つまらないです', 'それは 大きいです'], note: 'was は is の 過去の 形。', hint: 'was ＝ 〜でした。' },
    { stage: 3, lv: 2, unit: '夏の思い出', text: '"I enjoyed camping." の いみは？', choices: ['キャンプを 楽しみました', 'キャンプを 楽しみます', 'キャンプが きらいです', 'キャンプへ 行きます'], note: 'enjoyed ＝ 楽しんだ。', hint: '語の おわりの ed に 注目。' },
    { stage: 3, lv: 2, unit: '夏の思い出', text: '"I saw a beautiful sunset." の いみは？', choices: ['美しい 夕日を 見ました', '美しい 夕日を 見ます', '夕日が 好きです', '夕日は 明るいです'], note: 'saw は see の 過去の 形。', hint: 'saw ＝ 見た。' },
    { stage: 3, lv: 2, unit: '夏の思い出', text: '"How was your summer vacation?" の いみは？', choices: ['夏休みは どうでしたか', '夏休みは いつですか', '夏休みは 好きですか', '夏休みに 何を しますか'], note: 'How was 〜? ＝ 〜は どうでしたか。', hint: 'was ＝ 過去。' },
    { stage: 3, lv: 3, unit: '夏の思い出', text: '"I went to my grandmother\'s house and ate watermelon." の いみは？', choices: ['おばあさんの 家に 行って すいかを 食べました', 'おばあさんの 家で すいかを 作りました', 'おばあさんが 家へ 来ました', 'すいかを 買いに 行きます'], note: 'and で 二つの できごとを つなぎます。', hint: 'and ＝ そして。', boss: true },
    { stage: 3, lv: 3, unit: '夏の思い出', text: '「わたしは 花火を 見ました。とても きれいでした。」を 英語で 言うと？', choices: ['I saw fireworks. It was beautiful.', 'I see fireworks. It is beautiful.', 'I saw fireworks. It is beautiful.', 'I see fireworks. It was beautiful.'], note: '過去の こと なので saw と was。', hint: '二つとも 過去の 形。' },
    /* ===== 3 生き物と かん境 ===== */
    { stage: 3, lv: 1, unit: '生き物とかん境', text: '"Sea turtles live in the sea." の いみは？', choices: ['ウミガメは 海に すんで います', 'ウミガメは 川に すんで います', 'ウミガメを 見ました', 'ウミガメが 好きです'], note: 'live in 〜 ＝ 〜に すむ。', hint: 'live ＝ すむ。' },
    { stage: 3, lv: 1, unit: '生き物とかん境', text: '"Pandas eat bamboo." の いみは？', choices: ['パンダは 竹を 食べます', 'パンダは 竹の 中に います', 'パンダは 竹が きらいです', 'パンダを 見ました'], note: 'eat ＝ 食べる。', hint: 'bamboo ＝ 竹。' },
    { stage: 3, lv: 2, unit: '生き物とかん境', text: '"Frogs live in the pond." の いみは？', choices: ['カエルは 池に すんで います', 'カエルは 森に すんで います', 'カエルを 池で 見ました', 'カエルは 泳ぎます'], note: 'pond ＝ 池。', hint: 'pond ＝ 池。' },
    { stage: 3, lv: 2, unit: '生き物とかん境', text: '"We must protect the forest." の いみは？', choices: ['わたしたちは 森を 守らなければ なりません', '森へ 行きましょう', '森は 大きいです', '森が 好きです'], note: 'must ＝ 〜しなければ ならない。', hint: 'protect ＝ 守る。' },
    { stage: 3, lv: 2, unit: '生き物とかん境', text: '"Where do polar bears live?" に 合う 答えは？', choices: ['They live in the Arctic.', 'They eat fish.', 'Yes, they do.', 'It\'s cold.'], note: '場所を 聞かれて います。', hint: 'Where ＝ どこ。' },
    { stage: 3, lv: 3, unit: '生き物とかん境', text: '"Sea turtles eat plastic bags by mistake." の いみは？', choices: ['ウミガメは まちがえて ビニールぶくろを 食べて しまいます', 'ウミガメは ビニールぶくろが 好きです', 'ウミガメは ふくろを 運びます', 'ウミガメは 海で 遊びます'], note: 'by mistake ＝ まちがえて。かん境の 問題です。', hint: 'mistake ＝ まちがい。' },
    /* ===== 4 小学校の 思い出 ===== */
    { stage: 4, lv: 1, unit: '小学校の思い出', text: '"My best memory is our school trip." の いみは？', choices: ['いちばんの 思い出は 修学旅行です', '修学旅行に 行きたいです', '修学旅行は 楽しいです', '旅行が 好きです'], note: 'best memory ＝ いちばんの 思い出。', hint: 'memory ＝ 思い出。' },
    { stage: 4, lv: 1, unit: '小学校の思い出', text: '"What is your best memory?" の いみは？', choices: ['いちばんの 思い出は 何ですか', '思い出は いつですか', 'どこへ 行きましたか', 'だれと 行きましたか'], note: 'What ＝ 何。', hint: 'What ＝ 何。' },
    { stage: 4, lv: 1, unit: '小学校の思い出', text: '"We enjoyed the sports day." の いみは？', choices: ['わたしたちは 運動会を 楽しみました', '運動会が あります', '運動会に 行きます', '運動会は 楽しいです'], note: 'sports day ＝ 運動会。', hint: 'enjoyed ＝ 楽しんだ。' },
    { stage: 4, lv: 2, unit: '小学校の思い出', text: '"We sang songs at the music festival." の いみは？', choices: ['音楽会で 歌を 歌いました', '音楽会で 歌を 歌います', '音楽会が 好きです', '音楽会へ 行きます'], note: 'sang は sing の 過去の 形。', hint: 'sang ＝ 歌った。' },
    { stage: 4, lv: 2, unit: '小学校の思い出', text: '"It was exciting." の いみは？', choices: ['それは わくわくしました', 'それは しずかでした', 'それは かなしかったです', 'それは short でした'], note: 'exciting ＝ わくわくする。', hint: 'was ＝ 〜でした。' },
    { stage: 4, lv: 2, unit: '小学校の思い出', text: '"I enjoyed the school lunch." の いみは？', choices: ['給食を 楽しみました', '給食を 作りました', '給食が きらいです', '昼ごはんを 買いました'], note: 'school lunch ＝ 給食。', hint: 'lunch ＝ 昼食。' },
    { stage: 4, lv: 3, unit: '小学校の思い出', text: '「わたしの いちばんの 思い出は 運動会です」を 英語で 言うと？', choices: ['My best memory is the sports day.', 'My best memory is sports day are.', 'I best memory the sports day.', 'My memory best is sports day.'], note: 'My best memory is 〜. の 形。', hint: 'is の 位置。', boss: true },
    /* ===== 4 中学校で したい こと ===== */
    { stage: 4, lv: 1, unit: '中学校でしたいこと', text: '"I want to join the brass band." の いみは？', choices: ['ふきそうがく部に 入りたいです', 'ふきそうがく部を 見たいです', '音楽が 好きです', '楽器を 買いたいです'], note: 'brass band ＝ ふきそうがく部。', hint: 'join ＝ 加わる。' },
    { stage: 4, lv: 1, unit: '中学校でしたいこと', text: '"What club do you want to join?" の いみは？', choices: ['何部に 入りたいですか', '何が 好きですか', 'どこへ 行きますか', 'いつ 始めますか'], note: 'club ＝ 部活動。', hint: 'club ＝ 部。' },
    { stage: 4, lv: 2, unit: '中学校でしたいこと', text: '"I want to study English hard." の いみは？', choices: ['英語を いっしょうけんめい 勉強したいです', '英語が むずかしいです', '英語を 教えたいです', '英語が 好きです'], note: 'hard ＝ いっしょうけんめい。', hint: 'study ＝ 勉強する。' },
    { stage: 4, lv: 2, unit: '中学校でしたいこと', text: '"I want to be a vet." の いみは？', choices: ['じゅう医に なりたいです', '医者に なりたいです', '先生に なりたいです', '動物が 好きです'], note: 'vet ＝ じゅう医。', hint: '動物の お医者さん。' },
    { stage: 4, lv: 2, unit: '中学校でしたいこと', text: '"I want to make many friends." の いみは？', choices: ['たくさん 友だちを 作りたいです', '友だちと 遊びたいです', '友だちが 多いです', '友だちに 会いました'], note: 'make friends ＝ 友だちに なる。', hint: 'many ＝ たくさんの。' },
    { stage: 4, lv: 3, unit: '中学校でしたいこと', text: '"I want to join the tennis team because I like sports." の いみは？', choices: ['スポーツが 好きなので テニス部に 入りたいです', 'テニスが 好きなので スポーツを します', 'テニス部に 入りました', 'スポーツが 得意です'], note: 'because ＝ なぜなら。', hint: 'because の 後が 理由。', boss: true },
    /* ===== 追加の 問題（v10.9）===== */
    { stage: 1, lv: 1, unit: '自分のこと', text: '"Nice to meet you." に 返す ことばは？', choices: ['Nice to meet you, too.', 'You are welcome.', 'See you.', 'I\'m fine.'], note: 'はじめての あいさつの 返事です。', hint: 'too ＝ 〜も。' },
    { stage: 1, lv: 1, unit: '自分のこと', text: '"How do you spell your name?" の いみは？', choices: ['名前は どう つづりますか', '名前は 何ですか', '何さいですか', 'どこに 住んで いますか'], note: 'アルファベットで 一字ずつ 答えます。', hint: 'spell ＝ つづる。' },
    { stage: 1, lv: 1, unit: '日課', text: '"I brush my teeth." の いみは？', choices: ['歯を みがきます', '顔を あらいます', 'かみを とかします', '手を あらいます'], note: 'brush ＝ みがく、teeth ＝ 歯。', hint: 'teeth ＝ 歯。' },
    { stage: 1, lv: 1, unit: '日課', text: '"I take out the garbage." の いみは？', choices: ['ごみを 出します', 'ごみを ひろいます', 'そうじを します', '買い物に 行きます'], note: '家の 手つだいの 言い方です。', hint: 'garbage ＝ ごみ。' },
    { stage: 1, lv: 1, unit: '日課', text: '"What time is it?" に 合う 答えは？', choices: ['It\'s seven thirty.', 'It\'s Monday.', 'It\'s sunny.', 'I\'m seven.'], note: '時こくを 答えます。', hint: 'time ＝ 時こく。' },
    { stage: 1, lv: 2, unit: '日課', text: '"I wash the dishes every day." の いみは？', choices: ['毎日 食器を あらいます', '毎日 そうじを します', '毎日 料理を します', '毎日 買い物を します'], note: 'wash the dishes ＝ 食器を あらう。', hint: 'wash ＝ あらう。' },
    { stage: 1, lv: 2, unit: '日課', text: '"I do my homework before dinner." の いみは？', choices: ['夕食の 前に 宿題を します', '夕食の 後に 宿題を します', '宿題を しません', '夕食を 作ります'], note: 'before ＝ 〜の 前に。', hint: 'before ＝ 前。' },
    { stage: 1, lv: 2, unit: '自分のこと', text: '"I\'m good at drawing pictures." の いみは？', choices: ['絵を かくのが 得意です', '絵を 見るのが 好きです', '絵を 買いました', '絵が むずかしいです'], note: 'draw ＝ かく。', hint: 'drawing ＝ かく こと。' },
    { stage: 1, lv: 2, unit: '自分のこと', text: '"My favorite subject is science." の いみは？', choices: ['いちばん 好きな 教科は 理科です', '理科が むずかしいです', '理科を 勉強します', '理科の 先生です'], note: 'subject ＝ 教科。', hint: 'subject ＝ 教科。' },
    { stage: 1, lv: 2, unit: '日課', text: '"I usually take a bath at eight." の いみは？', choices: ['ふだん 8時に おふろに 入ります', 'ふだん 8時に ねます', '8時に 起きます', '8時に 家を 出ます'], note: 'take a bath ＝ おふろに 入る。', hint: 'bath ＝ おふろ。' },
    { stage: 1, lv: 3, unit: '自分のこと', text: '"I\'m from Japan. I live in Tokyo." の いみは？', choices: ['日本の 出身で 東京に 住んで います', '日本へ 行きます', '東京の 出身です', '日本が 好きです'], note: 'live in 〜 ＝ 〜に 住む。', hint: '二つの 文。' },
    { stage: 1, lv: 3, unit: '日課', text: '「わたしは ときどき 母を 手つだいます」を 英語で 言うと？', choices: ['I sometimes help my mother.', 'I always help my mother.', 'I help sometimes mother.', 'I am help my mother.'], note: 'sometimes は ふつう 動きを あらわす 語の 前。', hint: 'sometimes の 位置。' },
    { stage: 1, lv: 3, unit: '自分のこと', text: '"What do you do in your free time?" の いみは？', choices: ['ひまな 時間に 何を しますか', '仕事は 何ですか', 'どこに 行きますか', 'いつ 起きますか'], note: 'free time ＝ ひまな 時間。', hint: 'free ＝ 自由な。' },
    { stage: 1, lv: 1, unit: '自分のこと', text: '"How old are you?" に 合う 答えは？', choices: ['I\'m twelve years old.', 'I\'m from Japan.', 'It\'s Monday.', 'I like math.'], note: '年れいを 答えます。', hint: 'old ＝ 年れい。' },
    { stage: 1, lv: 2, unit: '自分のこと', text: '"I belong to the soccer club." の いみは？', choices: ['サッカー部に 入って います', 'サッカーが 好きです', 'サッカーを 見ます', 'サッカーが 得意です'], note: 'belong to 〜 ＝ 〜に 所ぞくして いる。', hint: 'belong ＝ 所ぞくする。' },
    { stage: 1, lv: 3, unit: '日課', text: '"I get up early on weekends." の いみは？', choices: ['週末は 早く 起きます', '週末は おそく 起きます', '週末は 出かけます', '毎日 早く 起きます'], note: 'weekend ＝ 週末、early ＝ 早く。', hint: 'early ＝ 早く。' },
    { stage: 2, lv: 1, unit: '行きたい国', text: '"I want to visit Australia." の いみは？', choices: ['オーストラリアを おとずれたいです', 'オーストラリアに 住んで います', 'オーストラリアが 好きです', 'オーストラリアへ 行きました'], note: 'visit ＝ おとずれる。', hint: 'visit ＝ 行く。' },
    { stage: 2, lv: 1, unit: '行きたい国', text: '"You can enjoy skiing in Canada." の いみは？', choices: ['カナダでは スキーを 楽しめます', 'カナダで スキーを しました', 'カナダは 寒いです', 'スキーが 好きです'], note: 'enjoy 〜ing ＝ 〜を 楽しむ。', hint: 'enjoy ＝ 楽しむ。' },
    { stage: 2, lv: 1, unit: '行きたい国', text: '"France is famous for its food." の いみは？', choices: ['フランスは 食べ物で 有名です', 'フランスの 食べ物が 好きです', 'フランスへ 行きます', 'フランスは 遠いです'], note: 'be famous for 〜 ＝ 〜で 有名だ。', hint: 'famous ＝ 有名。' },
    { stage: 2, lv: 2, unit: '行きたい国', text: '"You can see the Great Wall in China." の いみは？', choices: ['中国では 万里の長城を 見られます', '中国は 大きいです', '中国へ 行きました', 'かべを 作ります'], note: 'Great Wall ＝ 万里の長城。', hint: 'see ＝ 見る。' },
    { stage: 2, lv: 2, unit: '行きたい国', text: '"How about India?" の いみは？', choices: ['インドは どうですか', 'インドは どこですか', 'インドが 好きですか', 'インドへ 行きました'], note: 'How about 〜? ＝ 〜は どうですか。', hint: 'How about ＝ どう？' },
    { stage: 2, lv: 2, unit: '行きたい国', text: '"I want to eat curry in India." の いみは？', choices: ['インドで カレーを 食べたいです', 'インドの カレーが 好きです', 'カレーを 作ります', 'カレーを 食べました'], note: 'want to eat ＝ 食べたい。', hint: 'eat ＝ 食べる。' },
    { stage: 2, lv: 3, unit: '行きたい国', text: '"Why do you want to go to Egypt?" に 合う 答えは？', choices: ['Because I want to see the pyramids.', 'Yes, I do.', 'It\'s hot.', 'I am from Egypt.'], note: 'Because 〜 で 理由を 答えます。', hint: 'Because ＝ なぜなら。' },
    { stage: 2, lv: 3, unit: '行きたい国', text: '「わたしは ブラジルへ 行きたいです。サッカーを 見る ことが できます。」を 英語で 言うと？', choices: ['I want to go to Brazil. You can watch soccer.', 'I go to Brazil. You watch soccer.', 'I like Brazil. I watch soccer.', 'I am Brazil. You are soccer.'], note: 'watch ＝ (動く ものを) 見る。', hint: 'want to go と can。' },
    { stage: 2, lv: 1, unit: '住んでいる町', text: '"We have a nice beach." の いみは？', choices: ['すてきな 海岸が あります', '海岸へ 行きます', '海が 好きです', '海は 遠いです'], note: 'beach ＝ 海岸。', hint: 'have ＝ ある。' },
    { stage: 2, lv: 1, unit: '住んでいる町', text: '"Do you have a shopping mall?" に 合う 答えは？', choices: ['Yes, we do.', 'It\'s fun.', 'I like shopping.', 'It\'s ten.'], note: 'Do you have 〜? には Yes, we do. などで 答えます。', hint: 'Do you 〜? の 答え。' },
    { stage: 2, lv: 2, unit: '住んでいる町', text: '"We can enjoy hot springs here." の いみは？', choices: ['ここでは 温泉を 楽しめます', '温泉が 好きです', '温泉へ 行きました', '温泉は 熱いです'], note: 'hot spring ＝ 温泉。', hint: 'spring ＝ いずみ。' },
    { stage: 2, lv: 2, unit: '住んでいる町', text: '"My town is small but nice." の いみは？', choices: ['わたしの 町は 小さいけれど すてきです', 'わたしの 町は 大きいです', '町が 好きでは ありません', '町は 遠いです'], note: 'but ＝ しかし。', hint: 'but の 後。' },
    { stage: 2, lv: 2, unit: '住んでいる町', text: '"There is a big library near my house." の いみは？', choices: ['家の 近くに 大きな 図書館が あります', '図書館へ 行きます', '図書館が 好きです', '家は 大きいです'], note: 'There is 〜 ＝ 〜が ある。', hint: 'near ＝ 近く。' },
    { stage: 2, lv: 3, unit: '住んでいる町', text: '"I want a movie theater in my town." の いみは？', choices: ['町に 映画館が ほしいです', '映画を 見たいです', '映画館が あります', '映画が 好きです'], note: 'movie theater ＝ 映画館。', hint: 'want ＝ ほしい。' },
    { stage: 2, lv: 3, unit: '住んでいる町', text: '「わたしたちの 町には 病院が ありません」を 英語で 言うと？', choices: ['We don\'t have a hospital in our town.', 'We have a hospital in our town.', 'We are not a hospital.', 'I don\'t hospital our town.'], note: 'don\'t have ＝ ない。', hint: 'don\'t を 使う。' },
    { stage: 2, lv: 1, unit: '行きたい国', text: '"Where do you want to go?" に 合う 答えは？', choices: ['I want to go to Italy.', 'I like Italy.', 'It\'s Italy.', 'Yes, I do.'], note: 'I want to go to 〜. で 答えます。', hint: 'go to ＝ 行く。' },
    { stage: 2, lv: 2, unit: '行きたい国', text: '"It\'s a big country." の いみは？', choices: ['それは 大きな 国です', 'それは 小さな 町です', 'それは 遠い 国です', 'それは 有名です'], note: 'country ＝ 国。', hint: 'big ＝ 大きい。' },
    { stage: 2, lv: 3, unit: '住んでいる町', text: '"Our town has a long history." の いみは？', choices: ['わたしたちの 町には 長い 歴史が あります', '町は 新しいです', '町は 長いです', '歴史を 勉強します'], note: 'history ＝ 歴史。', hint: 'long ＝ 長い。' },
    { stage: 3, lv: 1, unit: '夏の思い出', text: '"I played soccer with my friends." の いみは？', choices: ['友だちと サッカーを しました', '友だちと サッカーを します', 'サッカーが 好きです', 'サッカーを 見ました'], note: 'played ＝ した。', hint: 'ed ＝ 過去。' },
    { stage: 3, lv: 1, unit: '夏の思い出', text: '"I visited my grandfather." の いみは？', choices: ['おじいさんを たずねました', 'おじいさんが 来ました', 'おじいさんが 好きです', 'おじいさんに 会います'], note: 'visited ＝ たずねた。', hint: 'visit ＝ たずねる。' },
    { stage: 3, lv: 1, unit: '夏の思い出', text: '"It was delicious." の いみは？', choices: ['それは おいしかったです', 'それは おいしいです', 'それは からいです', 'それは 大きいです'], note: 'was ＝ 〜でした。', hint: 'delicious ＝ おいしい。' },
    { stage: 3, lv: 2, unit: '夏の思い出', text: '"I went camping in the mountains." の いみは？', choices: ['山へ キャンプに 行きました', '山を 見ました', '山が 好きです', '山に 登ります'], note: 'go camping ＝ キャンプに 行く。', hint: 'went ＝ 行った。' },
    { stage: 3, lv: 2, unit: '夏の思い出', text: '"What did you do in summer?" の いみは？', choices: ['夏に 何を しましたか', '夏に 何を しますか', '夏は 好きですか', '夏は いつですか'], note: 'did ＝ 過去の 質問の 形。', hint: 'did ＝ 過去。' },
    { stage: 3, lv: 2, unit: '夏の思い出', text: '"I enjoyed the fireworks festival." の いみは？', choices: ['花火大会を 楽しみました', '花火を 買いました', '花火が 好きです', '花火を 見ます'], note: 'fireworks ＝ 花火。', hint: 'enjoyed ＝ 楽しんだ。' },
    { stage: 3, lv: 3, unit: '夏の思い出', text: '"How was the food?" に 合う 答えは？', choices: ['It was delicious.', 'It is delicious.', 'I like food.', 'Yes, I do.'], note: '過去の 質問には 過去で 答えます。', hint: 'was で 答える。' },
    { stage: 3, lv: 3, unit: '夏の思い出', text: '「わたしは 川で 泳ぎました。楽しかったです。」を 英語で 言うと？', choices: ['I swam in the river. It was fun.', 'I swim in the river. It is fun.', 'I swam in the river. It is fun.', 'I swim in the river. It was fun.'], note: 'swam は swim の 過去の 形。', hint: '二つとも 過去。' },
    { stage: 3, lv: 1, unit: '生き物とかん境', text: '"Penguins live in cold places." の いみは？', choices: ['ペンギンは 寒い ところに すんで います', 'ペンギンは 海が 好きです', 'ペンギンを 見ました', 'ペンギンは 泳ぎます'], note: 'place ＝ 場所。', hint: 'cold ＝ 寒い。' },
    { stage: 3, lv: 1, unit: '生き物とかん境', text: '"Koalas eat leaves." の いみは？', choices: ['コアラは 葉を 食べます', 'コアラは 木に います', 'コアラは ねて います', 'コアラが 好きです'], note: 'leaves ＝ 葉（leaf の 二つ いじょう）。', hint: 'leaf ＝ 葉。' },
    { stage: 3, lv: 2, unit: '生き物とかん境', text: '"Many animals are in danger." の いみは？', choices: ['多くの 動物が 危険な 状態に あります', '多くの 動物が 生まれました', '動物は 元気です', '動物を 助けました'], note: 'in danger ＝ 危険な 状態。', hint: 'danger ＝ 危険。' },
    { stage: 3, lv: 2, unit: '生き物とかん境', text: '"We should not throw away plastic." の いみは？', choices: ['プラスチックを すてては いけません', 'プラスチックを 使いましょう', 'プラスチックを 買いました', 'プラスチックは 便利です'], note: 'throw away ＝ すてる。', hint: 'should not ＝ 〜しては いけない。' },
    { stage: 3, lv: 2, unit: '生き物とかん境', text: '"Where do dolphins live?" に 合う 答えは？', choices: ['They live in the sea.', 'They eat fish.', 'It\'s big.', 'Yes, they do.'], note: '場所を 答えます。', hint: 'Where ＝ どこ。' },
    { stage: 3, lv: 3, unit: '生き物とかん境', text: '"Forests are important for animals." の いみは？', choices: ['森は 動物に とって 大切です', '森に 動物が います', '動物は 森が 好きです', '森を 作りましょう'], note: 'important ＝ 大切な。', hint: 'important ＝ 大切。' },
    { stage: 3, lv: 3, unit: '生き物とかん境', text: '「わたしたちは 海を きれいに するべきです」を 英語で 言うと？', choices: ['We should clean the sea.', 'We clean the sea should.', 'We should the sea clean.', 'We are clean the sea.'], note: 'should ＝ 〜するべきだ。', hint: 'should ＋ 動きの ことば。' },
    { stage: 3, lv: 1, unit: '夏の思い出', text: '"I was happy." の いみは？', choices: ['うれしかったです', 'うれしいです', 'かなしかったです', 'ねむいです'], note: 'was ＝ 〜でした。', hint: 'happy ＝ うれしい。' },
    { stage: 3, lv: 2, unit: '夏の思い出', text: '"I ate watermelon at the beach." の いみは？', choices: ['海岸で すいかを 食べました', '海岸で 泳ぎました', 'すいかを 買いました', '海が 好きです'], note: 'beach ＝ 海岸。', hint: 'ate ＝ 食べた。' },
    { stage: 3, lv: 2, unit: '生き物とかん境', text: '"Sea turtles need clean seas." の いみは？', choices: ['ウミガメには きれいな 海が 必要です', 'ウミガメは 海が 好きです', 'ウミガメを 見ました', '海を きれいに しました'], note: 'need ＝ 必要と する。', hint: 'need ＝ 必要。' },
    { stage: 4, lv: 1, unit: '小学校の思い出', text: '"We went to Kyoto on our school trip." の いみは？', choices: ['修学旅行で 京都へ 行きました', '京都へ 行きます', '京都が 好きです', '京都は 遠いです'], note: 'school trip ＝ 修学旅行。', hint: 'went ＝ 行った。' },
    { stage: 4, lv: 1, unit: '小学校の思い出', text: '"I liked the swimming class." の いみは？', choices: ['水泳の 授業が 好きでした', '水泳が とくいです', '水泳を します', '水泳を 見ました'], note: 'liked ＝ 好きだった。', hint: 'ed ＝ 過去。' },
    { stage: 4, lv: 1, unit: '小学校の思い出', text: '"We played dodgeball." の いみは？', choices: ['ドッジボールを しました', 'ドッジボールを します', 'ドッジボールが 好きです', 'ドッジボールを 見ました'], note: 'played ＝ した。', hint: 'ed ＝ 過去。' },
    { stage: 4, lv: 2, unit: '小学校の思い出', text: '"My best memory is the music festival." の いみは？', choices: ['いちばんの 思い出は 音楽会です', '音楽会に 行きたいです', '音楽会が ありました', '音楽が 好きです'], note: 'music festival ＝ 音楽会。', hint: 'memory ＝ 思い出。' },
    { stage: 4, lv: 2, unit: '小学校の思い出', text: '"We saw many temples." の いみは？', choices: ['たくさんの 寺を 見ました', 'たくさんの 寺が あります', '寺へ 行きます', '寺が 好きです'], note: 'temple ＝ 寺。', hint: 'saw ＝ 見た。' },
    { stage: 4, lv: 2, unit: '小学校の思い出', text: '"It was a good experience." の いみは？', choices: ['よい 経験でした', 'よい 天気でした', '楽しい 一日です', 'いい 場所です'], note: 'experience ＝ 経験。', hint: 'experience ＝ 経験。' },
    { stage: 4, lv: 3, unit: '小学校の思い出', text: '"What did you enjoy the most?" の いみは？', choices: ['いちばん 何を 楽しみましたか', '何が 好きですか', 'どこへ 行きましたか', 'いつ 行きましたか'], note: 'the most ＝ いちばん。', hint: 'most ＝ いちばん。' },
    { stage: 4, lv: 3, unit: '小学校の思い出', text: '「わたしたちは 運動会で リレーを しました」を 英語で 言うと？', choices: ['We ran a relay on the sports day.', 'We run a relay on the sports day.', 'We are run a relay.', 'We relay run sports day.'], note: 'ran は run の 過去の 形。', hint: 'ran ＝ 走った。' },
    { stage: 4, lv: 1, unit: '中学校でしたいこと', text: '"I want to join the art club." の いみは？', choices: ['美術部に 入りたいです', '美術館へ 行きたいです', '絵が 好きです', '絵を かきます'], note: 'art club ＝ 美術部。', hint: 'art ＝ 美術。' },
    { stage: 4, lv: 1, unit: '中学校でしたいこと', text: '"I want to read many books." の いみは？', choices: ['たくさんの 本を 読みたいです', 'たくさんの 本が あります', '本が 好きです', '本を 買いました'], note: 'many ＝ たくさんの。', hint: 'read ＝ 読む。' },
    { stage: 4, lv: 2, unit: '中学校でしたいこと', text: '"I want to be a doctor in the future." の いみは？', choices: ['将来 医者に なりたいです', '医者に 会いたいです', '医者は いそがしいです', '医者が 好きです'], note: 'in the future ＝ 将来。', hint: 'future ＝ 将来。' },
    { stage: 4, lv: 2, unit: '中学校でしたいこと', text: '"I want to try many things." の いみは？', choices: ['いろいろな ことに ちょうせんしたいです', 'たくさんの ものが ほしいです', 'いろいろな 人に 会いたいです', 'たくさん 食べたいです'], note: 'try ＝ ためす・ちょうせんする。', hint: 'try ＝ ためす。' },
    { stage: 4, lv: 2, unit: '中学校でしたいこと', text: '"What do you want to do at junior high school?" の いみは？', choices: ['中学校で 何を したいですか', '中学校は どこですか', '中学校は 楽しいですか', 'いつ 中学生に なりますか'], note: 'junior high school ＝ 中学校。', hint: 'junior high ＝ 中学。' },
    { stage: 4, lv: 3, unit: '中学校でしたいこと', text: '"I want to study science because I like experiments." の いみは？', choices: ['実験が 好きなので 理科を 勉強したいです', '理科が 好きなので 実験を します', '理科を 勉強しました', '実験が むずかしいです'], note: 'experiment ＝ 実験。', hint: 'because の 後が 理由。' },
    { stage: 4, lv: 3, unit: '中学校でしたいこと', text: '「わたしは 中学校で 英語を 勉強したいです」を 英語で 言うと？', choices: ['I want to study English at junior high school.', 'I want study English junior high school.', 'I am study English at junior high school.', 'I want to English study at junior high school.'], note: 'want to ＋ 動きの ことば。', hint: 'want to study。' },
    { stage: 4, lv: 1, unit: '小学校の思い出', text: '"Thank you for everything." の いみは？', choices: ['いろいろ ありがとう', 'また 会いましょう', 'はじめまして', 'ごめんなさい'], note: '卒業の ときの ことばです。', hint: 'thank you ＝ ありがとう。' },
    { stage: 4, lv: 2, unit: '中学校でしたいこと', text: '"I want to make new friends." の いみは？', choices: ['新しい 友だちを 作りたいです', '新しい 友だちが います', '友だちに 会いました', '友だちが 好きです'], note: 'make friends ＝ 友だちに なる。', hint: 'new ＝ 新しい。' },
    { stage: 4, lv: 3, unit: '小学校の思い出', text: '"We enjoyed our six years at this school." の いみは？', choices: ['この 学校での 6年間を 楽しみました', 'この 学校は 6年目です', '6年生です', '学校が 好きです'], note: 'six years ＝ 6年間。', hint: 'years ＝ 年。' },
    { stage: 4, lv: 2, unit: '小学校の思い出', text: '"I will never forget it." の いみは？', choices: ['けっして わすれません', 'わすれて しまいました', 'おぼえて いません', '思い出せません'], note: 'never forget ＝ けっして わすれない。', hint: 'forget ＝ わすれる。' }
  ]
};
